
name: alation publish
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm
        run: npm install
      - name: npm dependencies
        run: npm ci
        #Run an install with npm@5 or later
      - name: Test code
        run: npm run test